import { Properties as P } from "../ui-common/properties.slint";
import { Page, SettingsPage, DialogType, SystemUser } from "enumerations.slint";

import { SettingsMenu } from "widgets/settings-menu.slint";
import { OOBE } from "widgets/oobe.slint";
import { IconButton } from "../ui-common/iconbutton.slint";
import { HLine } from "../ui-common/hline.slint";
import { Toast } from "../ui-common/toast.slint";
import {
    VirtualKeyboard,
    VirtualKeyboardHandler,
    KeyModel,
} from "../ui-common/virtual_keyboard/virtual_keyboard.slint";
export { VirtualKeyboardHandler, KeyModel }

import { ScrollView } from "std-widgets.slint";

import { UserDialogs } from "widgets/settings-panels/users/dialogs.slint";

export component CoreSettings inherits Window {
    // Properties
    default-font-family <=> P.regular-font-family;
    default-font-size <=> P.default-font-size;
    background: #ffffff;

    in-out property <Page> page: Page.None;
    in-out property <SettingsPage> settings-page;
    in-out property <DialogType> dialog;
    in-out property <string> dialog-message;
    in-out property <SystemUser> selected-user;
    in-out property <int> dialog-millis-count;
    in-out property <bool> sticky-toast;

    in-out property <string> section-header-title: core-settings-header;
    in property <string> default-user;
    in property <[string]> users;
    in-out property <float> scaling-factor <=> P.scaling-factor;

    // Constants
    property <string> core-settings-header: "Core Settings";

    // Callbacks
    callback get-users();
    callback get-selected-user-details(string);
    callback change-user-password(string, string, string, bool);
    callback disable-storage-encryption(string, string);
    callback create-user(string, string, bool, bool, bool);
    callback quit();

    // UI
    ScrollView {
        mouse-drag-pan-enabled: true;
        if (page == Page.SettingsMenu): VerticalLayout {
            padding <=> P.layout-padding;
            spacing <=> P.layout-spacing;
            HorizontalLayout {
                if (settings-page == SettingsPage.None): IconButton {
                    icon: @image-url("../icons/x.svg");
                    border-radius <=> P.radius;
                    height <=> P.icon-button-height;
                    width: self.height;
                    y: (parent.height - self.height) / 2;
                    clicked => {
                        quit();
                    }
                }
                if (settings-page != SettingsPage.None): IconButton {
                    icon: @image-url("../icons/arrow-back.svg");
                    border-radius <=> P.radius;
                    height <=> P.icon-button-height;
                    width: self.height;
                    y: (parent.height - self.height) / 2;
                    clicked => {
                        settings-page = SettingsPage.None;
                        section-header-title = core-settings-header;
                    }
                }

                Rectangle { }

                Text {
                    text: section-header-title;
                    horizontal-alignment: center;
                    font-family <=> P.header-font-family;
                    font-weight: 800;
                    y: (parent.height - self.height) / 2;
                }

                Rectangle { }

                Rectangle {
                    height <=> P.icon-button-height;
                    width: self.height;
                }
            }

            if (page == Page.SettingsMenu): HLine {
                top-padding-multiplier: 1;
            }

            settings-menu := SettingsMenu {
                section-header-title <=> section-header-title;
                settings-page <=> settings-page;
                selected-user <=> selected-user;
                dialog <=> dialog;
                default-user <=> default-user;
                users <=> users;

                get-users => {
                    get-users();
                }

                get-selected-user-details(user) => {
                    get-selected-user-details(user);
                }
            }
        }

        if (page == Page.OOBE): OOBE {
            dialog <=> dialog;
            dialog-message <=> dialog-message;
            global-page <=> page;
            create-user(username, password, admin, quit-afterwards, make-default) => {
                create-user(username, password, admin, quit-afterwards, make-default);
            }
        }

        TouchArea {
            width: root.width;
            height: root.height;
            enabled: dialog != DialogType.None;
            clicked => {
                if !(dialog == DialogType.Toast && sticky-toast) {
                    TextInputInterface.text-input-focused = false;
                    dialog = DialogType.None;
                }
            }
        }

        if (dialog == DialogType.Toast): Toast {
            x: (parent.width - self.width) / 2;
            y: (parent.height - self.height) / 2;
            dialog-message <=> dialog-message;
        }

        if (dialog == DialogType.EncryptionConfirmPassword || dialog == DialogType.EncryptionChangePassword || dialog == DialogType.EncryptionNewPassword): UserDialogs {
            dialog <=> dialog;
            dialog-message <=> dialog-message;
            selected-user <=> selected-user;
            sticky-toast <=> sticky-toast;

            change-user-password(user, old-password, new-password, encrypted-storage-was-disabled) => {
                change-user-password(user, old-password, new-password, encrypted-storage-was-disabled);
            }

            disable-storage-encryption(user, password) => {
                disable-storage-encryption(user, password);
            }
        }
    }

    // Virtual keyboard
    ScrollView {
        VerticalLayout {
            alignment: end;
            visible: TextInputInterface.text-input-focused;
            changed visible => {
                if (self.visible == false) {
                    VirtualKeyboardHandler.current-key-set = 0;
                    i-keyboard.shift = false;
                }
            }
            i-keyboard := VirtualKeyboard {
                font-family: P.header-font-family;
                radius: P.radius;
                key-height: P.keyboard-key-height;
                scaling-factor: P.scaling-factor;
                close => {
                    TextInputInterface.text-input-focused = false;
                    dialog = DialogType.None;
                }
            }
        }
    }
}
