import { Properties as P } from "../../ui-common/properties.slint";
import { OOBEPage } from "../enumerations.slint";
import { Welcome } from "oobe/welcome.slint";
import { UserCreation } from "oobe/user-creation.slint";
import { DialogType } from "../enumerations.slint";

export component OOBE inherits VerticalLayout {
    callback create-user(string, string, bool);

    in-out property <OOBEPage> page: OOBEPage.Welcome;
    in-out property <DialogType> dialog;
    in-out property <string> dialog-message;

    if (page == OOBEPage.Welcome): Welcome {
        page <=> page;
    }

    if (page == OOBEPage.UserCreation): UserCreation {
        dialog <=> dialog;
        dialog-message <=> dialog-message;
        create-user(username, password, admin) => {
            create-user(username, password, admin);
        }
    }
}
