import { Properties as P } from "../../ui-common/properties.slint";
import { SettingsPage, SystemUser, DialogType } from "../enumerations.slint";

import { SectionButton } from "../../ui-common/sectionbutton.slint";
import {
    Users as UsersSettings,
} from "../widgets/settings-panels/users/users.slint";

export component SettingsMenu inherits VerticalLayout {
    in property <string> default-user;
    in-out property <[string]> users;

    in-out property <SettingsPage> settings-page: SettingsPage.None;
    in-out property <SystemUser> selected-user;
    in-out property <string> section-header-title;
    in-out property <DialogType> dialog;
    in-out property <string> dialog-message;
    in-out property <string> user-to-delete;
    in-out property <bool> admin-lock;

    callback get-users();
    callback get-selected-user-details(string);
    callback create-user(string, string, bool, bool, bool);
    callback make-admin(string);
    callback remove-admin(string);
    callback set-default-user(string);
    if (settings-page == SettingsPage.None): VerticalLayout {
        SectionButton {
            text: "Users & storage encryption";
            height: P.section-button-height;
            border-radius: P.radius;
            font-family: P.header-font-family;
            icon: @image-url("../../icons/key.svg");
            clicked => {
                get-users();
                section-header-title = self.text;
                selected-user.name = "";
                settings-page = SettingsPage.StorageEncryptionOptions;
            }
        }
    }

    if (settings-page == SettingsPage.StorageEncryptionOptions): UsersSettings {
        selected-user <=> selected-user;
        user-to-delete <=> user-to-delete;
        dialog <=> dialog;
        dialog-message <=> dialog-message;
        default-user <=> default-user;
        users <=> users;
        admin-lock <=> admin-lock;

        get-selected-user-details(string) => {
            get-selected-user-details(string);
        }

        make-admin(user) => {
            make-admin(user);
        }

        remove-admin(user) => {
            remove-admin(user);
        }

        set-default-user(user) => {
            set-default-user(user);
        }
    }
}
