import { Properties as P } from "../../../../ui-common/properties.slint";
import { DialogType, SystemUser } from "../../../enumerations.slint";

import { HLine } from "../../../../ui-common/hline.slint";
import { LineEdit } from "../../../../ui-common/lineedit.slint";
import { Button } from "../../../../ui-common/button.slint";
import { IconButton } from "../../../../ui-common/iconbutton.slint";
import { Switch } from "../../../../ui-common/switch.slint";

export component UserDialogs inherits Rectangle {
    in-out property <DialogType> dialog;
    in-out property <string> dialog-message;
    in-out property <SystemUser> selected-user;
    in-out property <bool> sticky-toast;

    callback change-user-password(string, string, string, bool);
    callback disable-storage-encryption(string, string);
    callback create-user(string, string, bool, bool, bool);
    callback admin-login-verify(string, string);

    border-width: P.dialog-rectangle-thickness;
    border-color: black;
    border-radius: P.radius;
    background: white;
    width: P.rwidth * 0.45;
    height: P.rheight * 0.4;
    x: (P.rwidth - self.width) / 2;
    y: P.rheight - self.height - P.approx-keyboard-height - P.space-between-keyboard-and-widget;
    TouchArea {
        width: parent.width;
        height: parent.height;
        enabled: true;
    }

    VerticalLayout {
        padding: P.layout-padding;
        HorizontalLayout {
            IconButton {
                icon: @image-url("../../../../icons/arrow-back.svg");
                border-radius: P.radius;
                height: P.icon-button-height;
                width: self.height;
                y: (parent.height - self.height) / 2;
                clicked => {
                    TextInputInterface.text-input-focused = false;
                    dialog = DialogType.None;
                }
            }

            Text {
                text: dialog == DialogType.ChangePassword ? "Changing password" : dialog == DialogType.ConfirmPassword ? "Confirming password" : dialog == DialogType.NewPassword ? "Setting password" : dialog == DialogType.NewUser ? "Creating user" : "Administrator login";
                font-family: P.header-font-family;
                font-size: P.default-font-size * P.dialog-sizes-multiplier;
                font-weight: P.bold-font-weight;
                wrap: word-wrap;
                horizontal-alignment: center;
                vertical-alignment: center;
            }

            Rectangle {
                height: P.icon-button-height;
                width: self.height;
                y: (parent.height - self.height) / 2;
            }
        }

        HLine {
            top-padding-multiplier: 4.0;
            bottom-padding-multiplier: self.top-padding-multiplier;
        }

        username-or-current-password-edit := LineEdit {
            default-height: dialog == DialogType.ChangePassword || dialog == DialogType.ConfirmPassword || dialog == DialogType.NewUser || dialog == DialogType.AdminLogin ? parent.height * 0.08 : 0;
            scaling-factor: P.scaling-factor;
            border-radius: P.radius;
            font-size: P.default-font-size * P.dialog-sizes-multiplier;
            placeholder-text: dialog == DialogType.NewUser || dialog == DialogType.AdminLogin ? "Username" : "Current password";
            input-type: dialog == DialogType.NewUser || dialog == DialogType.AdminLogin ? text : password;
            visible: dialog != DialogType.NewPassword;
        }

        Rectangle {
            vertical-stretch: dialog == DialogType.ChangePassword || dialog == DialogType.NewUser || dialog == DialogType.AdminLogin ? 0.05 : 0;
        }

        new-password-edit := LineEdit {
            default-height: parent.height * 0.08;
            scaling-factor: P.scaling-factor;
            border-radius: P.radius;
            font-size: P.default-font-size * P.dialog-sizes-multiplier;
            placeholder-text: dialog == DialogType.ChangePassword ? "New password" : "Password";
            visible: dialog == DialogType.ChangePassword || dialog == DialogType.NewPassword || dialog == DialogType.NewUser || dialog == DialogType.AdminLogin;
            input-type: password;
        }

        if (dialog == DialogType.NewPassword || dialog == DialogType.ChangePassword || dialog == DialogType.NewUser || dialog == DialogType.AdminLogin): Rectangle {
            vertical-stretch: 0.05;
        }

        confirm-password-edit := LineEdit {
            default-height: parent.height * 0.08;
            scaling-factor: P.scaling-factor;
            border-radius: P.radius;
            font-size: P.default-font-size * P.dialog-sizes-multiplier;
            placeholder-text: "Confirm password";
            visible: dialog == DialogType.ChangePassword || dialog == DialogType.NewPassword || dialog == DialogType.NewUser;
            input-type: password;
        }

        if (dialog == DialogType.NewUser): Rectangle {
            height: 20px;
        }

        HorizontalLayout {
            visible: dialog == DialogType.NewUser;
            Text {
                font-family: P.regular-font-family;
                text: "Default user";
                font-size: P.default-font-size * P.dialog-sizes-multiplier;
                vertical-alignment: center;
            }

            Rectangle { }

            make-default-switch := Switch {
                y: (parent.height - self.height) / 2;
                width: P.switch-width * P.dialog-sizes-multiplier;
                height: P.switch-height * P.dialog-sizes-multiplier;
                border-radius: P.radius;
                activated: false;
            }
        }

        Rectangle {
            vertical-stretch: 0.05;
            visible: dialog == DialogType.NewUser;
        }

        HorizontalLayout {
            visible: dialog == DialogType.NewUser;
            Text {
                font-family: P.regular-font-family;
                text: "Administrator";
                font-size: P.default-font-size * P.dialog-sizes-multiplier;
                vertical-alignment: center;
            }

            Rectangle { }

            make-admin-switch := Switch {
                y: (parent.height - self.height) / 2;
                width: P.switch-width * P.dialog-sizes-multiplier;
                height: P.switch-height * P.dialog-sizes-multiplier;
                border-radius: P.radius;
                activated: false;
            }
        }

        Rectangle { }

        Button {
            width: 100%;
            height: P.button-height * P.dialog-sizes-multiplier;
            font-family: P.header-font-family;
            font-size: P.default-font-size * P.dialog-sizes-multiplier;
            border-radius: P.radius;
            text: dialog == DialogType.AdminLogin ? "Log in" : "Confirm";
            clicked => {
                if username-or-current-password-edit.text.is-empty && dialog != DialogType.NewPassword {
                    if dialog == DialogType.NewUser || dialog == DialogType.AdminLogin {
                        dialog-message = "Please provide a username";
                    } else {
                        dialog-message = "Please provide current password";
                    }
                    dialog = DialogType.Toast;
                } else if new-password-edit.text != confirm-password-edit.text && (dialog == DialogType.ChangePassword || dialog == DialogType.NewPassword || dialog == DialogType.NewUser) {
                    dialog-message = "Passwords do not match";
                    dialog = DialogType.Toast;
                } else if new-password-edit.text == confirm-password-edit.text && new-password-edit.text.is-empty && (dialog == DialogType.ChangePassword || dialog == DialogType.NewPassword || dialog == DialogType.NewUser || dialog == DialogType.AdminLogin) {
                    dialog-message = "Password cannot be empty";
                    dialog = DialogType.Toast;
                } else {
                    if dialog == DialogType.NewUser {
                        dialog-message = "Creating user";
                    } else if dialog == DialogType.AdminLogin {
                        dialog-message = "Please wait";
                    } else if dialog == DialogType.ChangePassword || dialog == DialogType.NewPassword {
                        dialog-message = "Setting password";
                    } else if dialog == DialogType.ConfirmPassword {
                        dialog-message = "Disabling encrypted storage"
                    }
                    if dialog == DialogType.ChangePassword || dialog == DialogType.NewPassword {
                        change-user-password(selected-user.name, username-or-current-password-edit.text, new-password-edit.text, !selected-user.encryption);
                    } else if dialog == DialogType.ConfirmPassword {
                        disable-storage-encryption(selected-user.name, username-or-current-password-edit.text);
                    } else if dialog == DialogType.NewUser {
                        create-user(username-or-current-password-edit.text, new-password-edit.text, make-admin-switch.activated, false, make-default-switch.activated);
                    } else if dialog == DialogType.AdminLogin {
                        admin-login-verify(username-or-current-password-edit.text, new-password-edit.text);
                    }
                    sticky-toast = true;
                    dialog = DialogType.Toast;
                }
                TextInputInterface.text-input-focused = false;
            }
        }
    }
}
