import { Properties as P } from "../../../../ui-common/properties.slint";
import { DialogType, SystemUser } from "../../../enumerations.slint";

import { HLine } from "../../../../ui-common/hline.slint";
import { VLine } from "../../../../ui-common/vline.slint";
import { Switch } from "../../../../ui-common/switch.slint";
import { Button } from "../../../../ui-common/button.slint";
import { MinorButton } from "../../../../ui-common/minorbutton.slint";

import { ScrollView } from "std-widgets.slint";

export component Users inherits VerticalLayout {
    in-out property <[string]> users;
    in property <string> default-user;
    in-out property <SystemUser> selected-user;
    in-out property <DialogType> dialog;
    in-out property <string> dialog-message;
    in-out property <string> user-to-delete;
    in-out property <bool> admin-lock;

    property <string> show-prompt: "Tap to show";

    callback get-selected-user-details(string);

    HorizontalLayout {
        spacing: P.layout-spacing;
        ScrollView {
            mouse-drag-pan-enabled: true;
            width: 35%;
            VerticalLayout {
                spacing: P.layout-spacing;
                for username[index] in users: i-user-button := TouchArea {
                    i-user-container := Rectangle {
                        border-color: P.item-border-color;
                        border-radius: P.radius;
                        border-width: 3px;
                        background: username == selected-user.name ? P.item-selected-color : #ffffff;
                        HorizontalLayout {
                            padding: 20px;
                            spacing: P.layout-spacing * 1.5;
                            VerticalLayout {
                                alignment: center;
                                Image {
                                    source: @image-url("../../../../icons/user.svg");
                                    height: P.icon-button-height * 1.15;
                                    width: self.height;
                                    colorize: i-user-button.pressed ? #ffffff : #000000;
                                }
                            }

                            i-user-text := Text {
                                font-family: P.regular-font-family;
                                font-size: P.default-font-size * P.dialog-sizes-multiplier;
                                vertical-alignment: center;
                                wrap: word-wrap;
                                text: username;
                            }

                            VerticalLayout {
                                alignment: center;
                                Image {
                                    source: @image-url("../../../../icons/key.svg");
                                    height: P.icon-button-height * 1.15;
                                    width: self.height;
                                    colorize: i-user-button.pressed ? #ffffff : #000000;
                                }
                            }
                        }
                    }

                    states [
                        pressed when self.pressed: {
                            i-user-container.background: #000000;
                            i-user-text.color: #ffffff;
                        }
                    ]

                    clicked => {
                        get-selected-user-details(username);
                    }
                }
                Rectangle { }

                HLine {
                    thickness: 1px;
                }

                MinorButton {
                    text: "New user";
                    horizontal-text-alignment: left;
                    font-family: P.header-font-family;
                    font-size: P.header-font-size * 0.45;
                    font-weight: P.bold-font-weight;
                    layout-padding: 25px;
                    height: 80px;
                    show-icon: true;
                    icon: @image-url("../../../../icons/plus.svg");
                    enabled: !admin-lock;
                    clicked => {
                        TextInputInterface.text-input-focused = true;
                        dialog = DialogType.NewUser;
                    }
                }
            }
        }

        VLine {
            thickness: 2px;
        }

        if (selected-user.name.is-empty): VerticalLayout {
            alignment: center;
            Text {
                text: users.length == 0 ? "No users found" : "Select a user to manage its settings";
                horizontal-alignment: center;
                font-family: P.regular-font-family;
                wrap: word-wrap;
            }
        }
        if (!selected-user.name.is-empty): ScrollView {
            mouse-drag-pan-enabled: true;
            VerticalLayout {
                spacing: P.layout-spacing / P.dialog-sizes-multiplier;
                padding-top: self.spacing;
                padding-bottom: self.spacing;
                HorizontalLayout {
                    padding-left: P.layout-padding * P.dialog-sizes-multiplier;
                    padding-right: self.padding-left;
                    Text {
                        text: "Encryption";
                        vertical-alignment: center;
                    }

                    Switch {
                        y: (parent.height - self.height) / 2;
                        width: P.switch-width * P.dialog-sizes-multiplier;
                        height: P.switch-height * P.dialog-sizes-multiplier;
                        border-radius: P.radius;
                        activated: selected-user.encryption;
                        special-activation: true;
                        toggled => {
                            TextInputInterface.text-input-focused = true;
                            if selected-user.encryption {
                                dialog = DialogType.ConfirmPassword;
                            } else {
                                dialog = DialogType.NewPassword;
                            }
                        }
                    }
                }

                if (selected-user.encryption): HLine {
                    thickness: 1px;
                }

                if (selected-user.encryption): HorizontalLayout {
                    padding-left: P.layout-padding * P.dialog-sizes-multiplier;
                    padding-right: self.padding-left;
                    Text {
                        text: "Password";
                        vertical-alignment: center;
                    }

                    Button {
                        width: P.button-width * P.dialog-sizes-multiplier;
                        height: P.button-height * P.dialog-sizes-multiplier;
                        font-family: P.header-font-family;
                        font-size: P.default-font-size * P.dialog-sizes-multiplier;
                        border-radius: P.radius;
                        text: "Change";
                        clicked => {
                            TextInputInterface.text-input-focused = true;
                            dialog = DialogType.ChangePassword;
                        }
                    }
                }

                if (selected-user.encryption): HLine {
                    thickness: 1px;
                }

                if (selected-user.encryption): HorizontalLayout {
                    padding-left: P.layout-padding * P.dialog-sizes-multiplier;
                    padding-right: self.padding-left;
                    Text {
                        text: "Key";
                        vertical-alignment: center;
                    }

                    Rectangle {
                        width: 50px;
                    }

                    TouchArea {
                        property <bool> show: false;
                        Text {
                            width: parent.width;
                            text: show ? selected-user.encrypted-key : show-prompt;
                            font-family: P.console-font-family;
                            font-size: P.console-body-font-size;
                            wrap: char-wrap;
                            vertical-alignment: center;
                            horizontal-alignment: right;
                        }

                        clicked => {
                            show = !show;
                        }
                    }
                }

                if (selected-user.encryption): HLine {
                    thickness: 1px;
                }

                if (selected-user.encryption): HorizontalLayout {
                    padding-left: P.layout-padding * P.dialog-sizes-multiplier;
                    padding-right: self.padding-left;
                    Text {
                        text: "Salt";
                        vertical-alignment: center;
                    }

                    Rectangle {
                        width: 50px;
                    }

                    TouchArea {
                        property <bool> show: false;
                        Text {
                            width: parent.width;
                            text: show ? selected-user.salt : show-prompt;
                            font-family: P.console-font-family;
                            font-size: P.console-body-font-size;
                            wrap: char-wrap;
                            vertical-alignment: center;
                            horizontal-alignment: right;
                        }

                        clicked => {
                            show = !show;
                        }
                    }
                }

                HLine {
                    thickness: 1px;
                }

                HorizontalLayout {
                    padding-left: P.layout-padding * P.dialog-sizes-multiplier;
                    padding-right: self.padding-left;
                    Text {
                        text: "Default user";
                        vertical-alignment: center;
                    }

                    Rectangle {
                        width: 50px;
                    }

                    Text {
                        text: default-user == selected-user.name ? "Yes" : "No";
                        font-family: P.console-font-family;
                        font-size: P.console-body-font-size;
                        wrap: char-wrap;
                        vertical-alignment: center;
                        horizontal-alignment: right;
                    }
                }

                HLine {
                    thickness: 1px;
                }

                HorizontalLayout {
                    padding-left: P.layout-padding * P.dialog-sizes-multiplier;
                    padding-right: self.padding-left;
                    Text {
                        text: "Administrator";
                        vertical-alignment: center;
                    }

                    Rectangle {
                        width: 50px;
                    }

                    Text {
                        text: selected-user.admin ? "Yes" : "No";
                        font-family: P.console-font-family;
                        font-size: P.console-body-font-size;
                        wrap: char-wrap;
                        vertical-alignment: center;
                        horizontal-alignment: right;
                    }
                }

                HLine {
                    thickness: 1px;
                }

                HorizontalLayout {
                    padding-left: P.layout-padding * P.dialog-sizes-multiplier;
                    padding-right: self.padding-left;
                    Text {
                        text: "Special";
                        vertical-alignment: center;
                        color: !admin-lock ? #000000 : P.item-disabled-color;
                    }

                    Button {
                        width: P.button-width * P.dialog-sizes-multiplier;
                        height: P.button-height * P.dialog-sizes-multiplier;
                        font-family: P.header-font-family;
                        font-size: P.default-font-size * P.dialog-sizes-multiplier;
                        border-radius: P.radius;
                        text: "Delete";
                        enabled: !admin-lock;
                        clicked => {
                            user-to-delete = selected-user.name;
                            dialog-message = "This will delete all of this user's personal data.\n\nAre you sure you want to continue?";
                            dialog = DialogType.ConfirmUserDeletion;
                        }
                    }
                }

                Rectangle { }
            }
        }
    }
}
