import { MinorButton } from "../../../ui-common/minorbutton.slint";
import { OOBEPage } from "../../enumerations.slint";
import { Properties as P } from "../../../ui-common/properties.slint";

export component Welcome inherits VerticalLayout {
    alignment: center;
    spacing: P.layout-spacing;
    in-out property <OOBEPage> page;

    HorizontalLayout {
        alignment: center;
        Image {
            source: @image-url("../../../../../branding/quillos.svg");
            width: root.width * 0.4;
            height: self.width;
        }
    }

    Text {
        text: "Welcome";
        font-size: P.header-font-size * 2.75;
        font-family: "Playfair Display";
        font-weight: P.bold-font-weight;
        font-italic: true;
        horizontal-alignment: center;
    }

    Rectangle {
        height:  5 * P.layout-spacing;
    }

    HorizontalLayout {
        alignment: center;
        MinorButton {
            text: "Tap to set up";
            horizontal-text-alignment: left;
            font-family: P.header-font-family;
            font-size: P.header-font-size * 0.6;
            font-weight: P.bold-font-weight;
            layout-padding: 25px;
            width: P.rwidth * 0.4;
            height: P.rheight * 0.06;
            show-icon: true;
            invert-colorization: true;
            border-width: 4px;
            icon: @image-url("../../../icons/arrow-forward-700.svg");
            clicked => { 
                page = OOBEPage.UserCreation;
                TextInputInterface.text-input-focused = true;
            }
        }
    }
}
